server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: url-shortener
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/url_shortener}
    username: ${POSTGRES_USER:url_shortener}
    password: ${POSTGRES_PASSWORD:url_shortener}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
